### ISSUE TITLE
ValueError: unknown url type: 'status'

### ISSUE THREAD

**Issue by 3xTpA** [Dibakarroy1997/365datascience_downloader#1]
Downloading C:\Users\Mortada_Cherrak\Downloads\365DataScience\Introduction to Data and Data Science\intro-to-data-and-data-science_0.zip...
Traceback (most recent call last):
  File "C:\Users\Mortada_Cherrak\Music\Script\365datascience_downloader\src\download_single_course.py", line 136, in <module>
    download_course_resource(course_url=course_url,
  File "C:\Users\Mortada_Cherrak\Music\Script\365datascience_downloader\src\download_single_course.py", line 126, in download_course_resource
    urllib.request.urlretrieve(course_resource_url, file_path)
  File "C:\Users\Mortada_Cherrak\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mortada_Cherrak\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mortada_Cherrak\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 503, in open
    req = Request(fullurl, data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mortada_Cherrak\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 322, in __init__
    self.full_url = url
    ^^^^^^^^^^^^^
  File "C:\Users\Mortada_Cherrak\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 348, in full_url
    self._parse()
  File "C:\Users\Mortada_Cherrak\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'status'

**Comment by Dibakarroy1997** [comment]
This happens if the server response if not OK (200).

I added `raise_for_status` so that this exception is thrown early.

One way to solve it is regenerate `refreshToken` and run script again.

**Comment by Pokenda** [comment]
Not sure if I should post here or open a new issue. I am new to this.

C:\Users\vital\Downloads\365datascience_downloa\venv\Scripts\python.exe C:\Users\vital\Downloads\365datascience_downloa\src\365datascience_course_downloader\download_single_course.py 
Downloading C:\Users\vital\Downloads\365DataScience\Web Scraping and API Fundamentals in Python\web-scraping-and-api-fundamentals-in-python_0.zip...
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
[info] master: Downloading 1 format(s): 2982+audio-3-en__Main_
ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
Traceback (most recent call last):
  File "C:\Users\vital\Downloads\365datascience_downloa\src\365datascience_course_downloader\download_single_course.py", line 132, in <module>
    download_course(
  File "C:\Users\vital\Downloads\365datascience_downloa\src\365datascience_course_downloader\download_single_course.py", line 104, in download_course
    download_video_from_stream_url(master_m3u8_url, file_path, quality)
  File "C:\Users\vital\Downloads\365datascience_downloa\src\365datascience_course_downloader\download_single_course.py", line 31, in download_video_from_stream_url
    ydl.download(video_stream_url)
  File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 3318, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 3293, in wrapper
    res = func(*args, **kwargs)
  File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1466, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1574, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1632, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 2733, in process_video_result
    self.process_info(new_info)
  File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 3154, in process_info
    self.report_error(f'{msg}. Aborting due to --abort-on-error')
  File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 996, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 936, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error



It downloaded a zip file with course recourses but no video.
Installing ffmpeg package in PyCharm didn't still throws an error.

**Comment by Dibakarroy1997** [comment]
> Not sure if I should post here or open a new issue. I am new to this.
> 
> C:\Users\vital\Downloads\365datascience_downloa\venv\Scripts\python.exe C:\Users\vital\Downloads\365datascience_downloa\src\365datascience_course_downloader\download_single_course.py 
> Downloading C:\Users\vital\Downloads\365DataScience\Web Scraping and API Fundamentals in Python\web-scraping-and-api-fundamentals-in-python_0.zip...
> [generic] master: Downloading webpage
> [generic] master: Downloading m3u8 information
> [info] master: Downloading 1 format(s): 2982+audio-3-en__Main_
> ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
> Traceback (most recent call last):
>   File "C:\Users\vital\Downloads\365datascience_downloa\src\365datascience_course_downloader\download_single_course.py", line 132, in <module>
>     download_course(
>   File "C:\Users\vital\Downloads\365datascience_downloa\src\365datascience_course_downloader\download_single_course.py", line 104, in download_course
>     download_video_from_stream_url(master_m3u8_url, file_path, quality)
>   File "C:\Users\vital\Downloads\365datascience_downloa\src\365datascience_course_downloader\download_single_course.py", line 31, in download_video_from_stream_url
>     ydl.download(video_stream_url)
>   File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 3318, in download
>     self.__download_wrapper(self.extract_info)(
>   File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 3293, in wrapper
>     res = func(*args, **kwargs)
>   File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1466, in extract_info
>     return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
>   File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1477, in wrapper
>     return func(self, *args, **kwargs)
>   File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1574, in __extract_info
>     return self.process_ie_result(ie_result, download, extra_info)
>   File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1632, in process_ie_result
>     ie_result = self.process_video_result(ie_result, download=download)
>   File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 2733, in process_video_result
>     self.process_info(new_info)
>   File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 3154, in process_info
>     self.report_error(f'{msg}. Aborting due to --abort-on-error')
>   File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 996, in report_error
>     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
>   File "C:\Users\vital\Downloads\365datascience_downloa\venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 936, in trouble
>     raise DownloadError(message, exc_info)
> yt_dlp.utils.DownloadError: ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
> 
> 
> 
> It downloaded a zip file with course recourses but no video.
> Installing ffmpeg package in PyCharm still throws an error.

You need to download ffmpeg and add it to the system path: https://www.wikihow.com/Install-FFmpeg-on-Windows

**Comment by hishamoo22** [comment]
to be honest i don't much about python yet but im getting this error message 


 File "*****365datascience_downloader-main\365datascience_downloader-main\src\365datascience_course_downloader\download_single_course.py", line 46, in request_365datascience_course_api
    return CourseModel.parse_raw(response.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 549, in pydantic.main.BaseModel.parse_raw
  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 7 validation errors for CourseModel
id
  field required (type=value_error.missing)
slug
  field required (type=value_error.missing)
info
  field required (type=value_error.missing)
examId
  field required (type=value_error.missing)
stats
  field required (type=value_error.missing)
nextLecture
  field required (type=value_error.missing)
sections
  field required (type=value_error.missing)

**Comment by debakarr** [comment]
@Pokenda Updated Readme. Will be closing this issue.
